export { default as Home} from './Home/home'
export { default as Contact} from './Contact/contact'
export { default as Products} from './Products/products'
export { default as Login} from './Sign_In'
export { default as SignUp} from './Sign_Up'
export { default as AdminPage } from './admin'
export { default as DK} from './DK/DK'